-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgr4/UFohtTcTMZGUc7CyWPaYEXuwgTXk3gtRc/7XhYbKgCgYIKoZIzj0DAQehRANCAAQ8IZXvOMeyPvs1QiMbubfYfZTHIULvWUm7Zh2K8iewvZbMepJlB+QEUGJPoGAkA90GfsT+wlgPcMFYYrd/6kit
-----END PRIVATE KEY-----